# Generated by Django 2.2.4 on 2019-08-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190814_0551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='CurrentYear',
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_pic'),
        ),
    ]
