# Generated by Django 2.2.4 on 2019-08-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190814_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='time',
            field=models.DateField(auto_now=True),
        ),
    ]
