# Generated by Django 2.2.4 on 2019-08-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearAndTotalLeaveAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_year', models.PositiveIntegerField(default=2019)),
                ('total_leave_available', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='leave_saved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='leave_taken',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
