# Generated by Django 2.2.4 on 2019-08-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190820_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearandtotalleaveavailable',
            name='current_year',
            field=models.PositiveIntegerField(default=2019),
        ),
        migrations.AddField(
            model_name='yearandtotalleaveavailable',
            name='total_leave_available',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
