# Generated by Django 2.2.4 on 2019-08-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190820_0427'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YearAndTotalLeaveAvailable',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='leave_saved',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='leave_taken',
        ),
        migrations.AddField(
            model_name='customuser',
            name='on_leave_till',
            field=models.DateField(auto_now=True),
        ),
    ]
