# Generated by Django 2.2.4 on 2019-08-22 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190822_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='on_leave_till',
            field=models.DateField(blank=True, default=datetime.date(2019, 8, 22)),
        ),
    ]
