# Generated by Django 2.2.4 on 2019-08-19 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave_type', '0001_initial'),
        ('applications', '0003_auto_20190816_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='leave_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave_type.LeaveModel'),
        ),
    ]
