# Generated by Django 2.2.4 on 2019-08-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_applicationmodel_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='attachment',
            field=models.FileField(blank=True, upload_to='attachment/'),
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('DENAYED', 'Denayed'), ('PANDING', 'Panding')], default='PANDING', max_length=100),
        ),
    ]
