# Generated by Django 2.2.4 on 2019-08-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=250)),
                ('leave_criteria', models.TextField()),
                ('leave_number_of_days', models.PositiveIntegerField()),
            ],
        ),
    ]
