# Generated by Django 2.2.4 on 2019-08-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_type', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavemodel',
            name='leave_number_of_days',
        ),
        migrations.AddField(
            model_name='leavemodel',
            name='leave_depands_on_working_days',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavemodel',
            name='leave_months_per_year',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='leavemodel',
            name='leave_number_of_months',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='leavemodel',
            name='leave_salary_type',
            field=models.CharField(choices=[('FULL', 'Full'), ('HALF', 'Half'), ('NO', 'No')], default='FULL', max_length=250),
        ),
    ]
